apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-8
  template:
    metadata:
      labels:
        app: mysql-8
    spec:
      containers:
      - image: mysql:8
        name: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: magadiflo
          - name: MYSQL_DATABASE
            value: db_dk_ms_users