apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-postgres
spec:
  volumeName: persistent-volume-postgres
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi