apiVersion: v1
kind: Secret
metadata:
  name: dk-ms-users
type: Opaque
data:
  data_base_username: cm9vdA==
  data_base_password: bWFnYWRpZmxv

---

apiVersion: v1
kind: Secret
metadata:
  name: dk-ms-courses
type: Opaque
data:
  data_base_username: cG9zdGdyZXM=
  data_base_password: bWFnYWRpZmxv