apiVersion: v1
kind: Service
metadata:
  name: dk-ms-spring-cloud-gateway
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: dk-ms-spring-cloud-gateway
  type: LoadBalancer