server:
  port: ${CONTAINER_PORT:8090}

spring:
  application:
    name: dk-ms-spring-cloud-gateway

  cloud:
    gateway:
      routes:
        - id: dk-ms-courses
          uri: lb://dk-ms-courses
          predicates:
            - Path=/base-courses/**
          filters:
            - StripPrefix=1
        - id: dk-ms-users
          uri: lb://dk-ms-users
          predicates:
            - Path=/base-users/**
          filters:
            - StripPrefix=1