server:
  port: ${CONTAINER_PORT:8001}
  error:
    include-message: always

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

custom:
  course-service:
    base-url: http://c-course-service:8002/api/v1/courses

logging:
  level:
    dev.magadiflo.user.app: debug
    org.hibernate.SQL: debug
  file:
    name: /app/logs/${spring.application.name}.log
