server:
  port: 8001
  error:
    include-message: always

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_user_service
    username: admin
    password: magadiflo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

custom:
  course-service:
    base-url: http://localhost:8002/api/v1/courses

logging:
  level:
    dev.magadiflo.user.app: debug
    org.hibernate.SQL: debug
