server:
  port: ${CONTAINER_PORT:8002}
  error:
    include-message: always

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

custom:
  service:
    user-service:
      url: ${USER_CLIENT_HOST}:${USER_CLIENT_PORT}

logging:
  level:
    dev.magadiflo.course.app: DEBUG
    org.hibernate.SQL: DEBUG