server:
  port: 8002
  error:
    include-message: always

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://c-postgres:5432/db_course_service
    username: postgres
    password: magadiflo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

custom:
  user-service:
    base-url: http://c-user-service:8001/api/v1/users

logging:
  level:
    dev.magadiflo.course.app: debug
    org.hibernate.SQL: debug
