server:
  port: ${CONTAINER_PORT:8002}
  error:
    include-message: always

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

custom:
  user-service:
    base-url: http://${USER_SERVICE_HOST}:${USER_SERVICE_PORT}/api/v1/users

logging:
  level:
    dev.magadiflo.course.app: debug
    org.hibernate.SQL: debug
