server:
  port: ${CONTAINER_PORT:8002}

spring:
  application:
    name: dk-ms-courses

  datasource:
    url: jdbc:postgresql://${DATA_BASE_HOST}:${DATA_BASE_PORT}/${DATA_BASE_NAME}
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true

logging:
  level:
    org.hibernate.SQL: debug
  file:
    name: /app/logs/dk-ms-courses.log
