apiVersion: v1
kind: Service
metadata:
  name: s-authorization-server
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: d-authorization-server
  type: LoadBalancer
