server:
  port: ${CONTAINER_PORT:8001}
  error:
    include-message: always

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    dev.magadiflo.user.app: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: /app/logs/${spring.application.name}.log