server:
  port: ${CONTAINER_PORT:8001}

spring:
  application:
    name: dk-ms-users

  datasource:
    url: jdbc:mysql://${DATA_BASE_HOST}:${DATA_BASE_PORT}/${DATA_BASE_NAME}
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
  file:
    name: /app/logs/dk-ms-users.log
